/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApolloLogoBlue: typeof import('./src/components/user/basic/ApolloLogoBlue.vue')['default']
    ApolloLogoNormal: typeof import('./src/components/user/basic/ApolloLogoNormal.vue')['default']
    CircleBottom: typeof import('./src/components/login/basic/CircleBottom.vue')['default']
    CircleTop: typeof import('./src/components/login/basic/CircleTop.vue')['default']
    CloudflareChecker: typeof import('./src/components/login/basic/CloudflareChecker.vue')['default']
    CloudflareLogoText: typeof import('./src/components/icons/CloudflareLogoText.vue')['default']
    CloudflareTurnstile: typeof import('./src/components/CloudflareTurnstile.vue')['default']
    Container: typeof import('./src/components/login/container/Container.vue')['default']
    DayNightToggleButton: typeof import('./src/components/dayNightToggleButton/DayNightToggleButton.vue')['default']
    Divider: typeof import('./src/components/login/basic/Divider.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputLong: typeof import('./src/components/login/basic/InputLong.vue')['default']
    InputShort: typeof import('./src/components/Input/InputShort.vue')['default']
    LeftSide: typeof import('./src/components/user/security/userContainer/leftSide/LeftSide.vue')['default']
    LeftSideMenu: typeof import('./src/components/user/basic/LeftSideMenu.vue')['default']
    LoginPage: typeof import('./src/components/login/LoginPage.vue')['default']
    PngIcon: typeof import('./src/components/PngIcon.vue')['default']
    RightContent: typeof import('./src/components/user/security/userContainer/rightContent/RightContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/login/setting/Settings.vue')['default']
    ShellButton: typeof import('./src/components/login/basic/ShellButton.vue')['default']
    Side: typeof import('./src/components/login/side/Side.vue')['default']
    SuccessIcon: typeof import('./src/components/icons/SuccessIcon.vue')['default']
    ThirdPartyButton: typeof import('./src/components/login/basic/ThirdPartyButton.vue')['default']
    TokenScopeSelector: typeof import('./src/components/user/basic/dialog/accountSecurity/TokenScopeSelector.vue')['default']
    UserAccountSecurityActionDialogBody: typeof import('./src/components/user/basic/dialog/accountSecurity/UserAccountSecurityActionDialogBody.vue')['default']
    UserAccountSecurityActionDialogHeader: typeof import('./src/components/user/basic/dialog/accountSecurity/UserAccountSecurityActionDialogHeader.vue')['default']
    UserActionCard: typeof import('./src/components/user/security/userContainer/rightContent/UserActionCard.vue')['default']
    UserActionDialog: typeof import('./src/components/user/basic/UserActionDialog.vue')['default']
    UserContainer: typeof import('./src/components/user/security/userContainer/UserContainer.vue')['default']
    UserHead: typeof import('./src/components/user/security/userHead/UserHead.vue')['default']
    UserPage: typeof import('./src/components/user/security/UserPage.vue')['default']
    UserPasskeysActionDialogBody: typeof import('./src/components/user/basic/dialog/passkeys/UserPasskeysActionDialogBody.vue')['default']
    UserPasskeysActionDialogHeader: typeof import('./src/components/user/basic/dialog/passkeys/UserPasskeysActionDialogHeader.vue')['default']
    UserThirdPartyAccountsActionDialogBody: typeof import('./src/components/user/basic/dialog/thirdPartyAccounts/UserThirdPartyAccountsActionDialogBody.vue')['default']
    UserThirdPartyAccountsActionDialogHeader: typeof import('./src/components/user/basic/dialog/thirdPartyAccounts/UserThirdPartyAccountsActionDialogHeader.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
