name = "jian-unified-system-Vue-worker"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
pages_build_output_dir = "dist"

[[routes]]
route = "/api/*"
type = "forward"