/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedValue: typeof import('./src/components/common/AnimatedValue.vue')['default']
    ApolloThemeToggle: typeof import('./src/components/common/ApolloThemeToggle.vue')['default']
    AppSettingsPanel: typeof import('./src/components/common/AppSettingsPanel.vue')['default']
    AppSidebar: typeof import('./src/components/common/AppSidebar.vue')['default']
    ArrowDropDownIcon: typeof import('./src/components/common/ArrowDropDownIcon.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ErrorBanner: typeof import('./src/components/common/ErrorBanner.vue')['default']
    GoogleSheetsImport: typeof import('./src/components/GoogleSheetsImport.vue')['default']
    IncomeFilters: typeof import('./src/components/income/IncomeFilters.vue')['default']
    IncomeInsights: typeof import('./src/components/income/IncomeInsights.vue')['default']
    InvoiceShell: typeof import('./src/components/invoice/InvoiceShell.vue')['default']
    MonthNavigator: typeof import('./src/components/income/MonthNavigator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SheetPreview: typeof import('./src/components/income/SheetPreview.vue')['default']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
    TopBar: typeof import('./src/components/common/TopBar.vue')['default']
    TranslateIcon: typeof import('./src/components/common/TranslateIcon.vue')['default']
    TrendChart: typeof import('./src/components/income/TrendChart.vue')['default']
    WeeklyCalendar: typeof import('./src/components/income/WeeklyCalendar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
